name: "Update Package Version Workflow"

on:
  workflow_call:
    secrets:
      GITHUB_REPO_PAT:
        required: true
    inputs:
      package_json_path:
        required: true
        type: string

jobs:
  update-version:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory '*'
      - name: 🤖 Git config
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_REPO_PAT }}

      - name: 👁️ Determine Merged Branch Name
        id: branch_name
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          BRANCH_NAME=$(echo "$COMMIT_MESSAGE" | sed -n 's/Merge pull request #[0-9]* from imenesesl\/\([^ ]*\).*/\1/p')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Extracted branch name: $BRANCH_NAME"

      - name: 🔎 Determine Increment Type
        id: increment_type
        run: |
          BRANCH_NAME="${{ env.BRANCH_NAME }}"
          PREFIX="${BRANCH_NAME%%/*}"
          
          case "$PREFIX" in
            "fix"|"hotfix"|"feature"|"feat"|"core")
              echo "INCREMENT_TYPE=$PREFIX" >> $GITHUB_ENV
              ;;
            *)
              echo "INCREMENT_TYPE=fix" >> $GITHUB_ENV
              ;;
          esac

      - name: 🔃 Update Package Version
        uses: imenesesl/heroku-workflow@main
        with:
          args: "update-version"
        env:
          PACKAGE_JSON_PATH: ${{ inputs.package_json_path }}
          INCREMENT_TYPE: ${{ env.INCREMENT_TYPE }}

      - name: 🆕 Commit and Push Version Update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "bump:app-package-version"
          git push
