name: "Update Package Version Workflow"

on:
  workflow_call:
    secrets:
      GITHUB_REPO_PAT:
        required: true
    inputs:
      package_json_path:
        required: true
        type: string

jobs:
  update-version:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory '*'
      - name: 🤖 Git config
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_REPO_PAT }}

      - name: 🔎 Determine Increment Type
        id: increment_type
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          PREFIX="${BRANCH_NAME%%/*}"
          if [[ "$PREFIX" == "fix" ]]; then
            echo "INCREMENT_TYPE=fix" >> $GITHUB_ENV
          elif [[ "$PREFIX" == "hotfix" ]]; then
            echo "INCREMENT_TYPE=hotfix" >> $GITHUB_ENV
          elif [[ "$PREFIX" == "feature" ]]; then
            echo "INCREMENT_TYPE=feature" >> $GITHUB_ENV
          elif [[ "$PREFIX" == "core" ]]; then
            echo "INCREMENT_TYPE=core" >> $GITHUB_ENV
          else
            echo "INCREMENT_TYPE=fix" >> $GITHUB_ENV
          fi

      - name: 🔃 Update Package Version
        uses: imenesesl/heroku-workflow@main
        with:
          args: "update-version"
        env:
          PACKAGE_JSON_PATH: ${{ inputs.package_json_path }}
          INCREMENT_TYPE: ${{ env.INCREMENT_TYPE }}

      - name: 🆕 Commit and Push Version Update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "bump:app-package-version"
          git push
